# Generated by Django 3.0.5 on 2021-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0003_auto_20210617_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
