# Generated by Django 3.0.5 on 2021-07-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0005_auto_20210618_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=130)),
                ('Number_of_pizza', models.IntegerField()),
                ('Grand_total', models.IntegerField()),
            ],
        ),
    ]
