# Generated by Django 3.0.5 on 2021-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0007_auto_20210707_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='build/static/media'),
        ),
    ]
