# Generated by Django 3.0.5 on 2021-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0008_auto_20210707_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='react-cart/build/static/media'),
        ),
    ]
