# Generated by Django 3.0.5 on 2021-07-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0009_auto_20210707_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='react-cart/build/static/images'),
        ),
    ]
