# Generated by Django 3.0.5 on 2021-06-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
